server_list:
  Entity1:
    description: Small description for Entity1
    elements:
      group1:
        - name: Server1
          isaws: false
        - name: Server2
          isaws: true
        - name: Server3
          isaws: false
      group2:
        - name: Server1
          isaws: true
        - name: Server2
          isaws: false
        - name: Server3
          isaws: true
  Entity1:
    description: Small description for Entity1
    elements:
      group1:
        - name: Server1
          isaws: false
        - name: Server2
          isaws: true
        - name: Server3
          isaws: false
      group2:
        - name: Server1
          isaws: true
        - name: Server2
          isaws: false
        - name: Server3
          isaws: true
